In [1]:
import pandas as pd
import numpy as np

## 1. READ DATASET FALL DETECTION

In [2]:
df_fall = pd.read_csv("falldetection.csv")
#nampilin 5 data pertama dari csv, jumlah data bisa disesuain di parameternya
df_fall.head()

ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
0         3  4722.92   4019.64 -1600.00  13   79          317
1         2  4059.12   2191.03 -1146.08  20   54          165
2         2  4773.56   2787.99 -1263.38  46   67          224
3         4  8271.27   9545.98 -2848.93  26  138          554
4         4  7102.16  14148.80 -2381.15  85  120          809

In [3]:
df_fall.dtypes

ACTIVITY         int64
TIME           float64
SL             float64
EEG            float64
BP               int64
HR               int64
CIRCLUATION      int64
dtype: object

In [4]:
#cek berapa bnyk record datanya
len(df_fall)

16382

In [5]:
#cek berapa banyak elemen datanya
df_fall.count

<bound method DataFrame.count of        ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
0             3  4722.92   4019.64 -1600.00  13   79          317
1             2  4059.12   2191.03 -1146.08  20   54          165
2             2  4773.56   2787.99 -1263.38  46   67          224
3             4  8271.27   9545.98 -2848.93  26  138          554
4             4  7102.16  14148.80 -2381.15  85  120          809
...         ...      ...       ...      ...  ..  ...          ...
16377         4  9280.68  11417.00 -3021.64  36  156          654
16378         3  8479.69   9455.54 -2932.85  17  138          554
16379         2  8872.53  27449.90 -2870.00  33  156         1364
16380         4  7738.99  26466.40 -2920.24  97  156         1521
16381         3  9368.34  39149.10 -2970.00  21  196         1885

[16382 rows x 7 columns]>

## 2. PREPROCESSING FALL DETECTION

In [6]:
df_fall.isnull().sum()

ACTIVITY       0
TIME           0
SL             0
EEG            0
BP             0
HR             0
CIRCLUATION    0
dtype: int64

karena datanya tidak ada yg null ataupun berbentun nan, maka tidak ada data yg perlu dihapus atau direplace

## 3. KLASIFIKASI FALL DETECTION

### Naive Bayes

In [7]:
#Menentukan Variabel Independen dan Dependen 
#Variabel independen
x = df_fall.drop(["ACTIVITY"], axis = 1)
x.head()

#Variabel dependen
y = df_fall["ACTIVITY"]
y.head()

0    3
1    2
2    2
3    4
4    4
Name: ACTIVITY, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [9]:
from sklearn.naive_bayes import GaussianNB
#Mengaktifkan/memanggil/membuat fungsi klasifikasi naive bayes
modelnb = GaussianNB()

#Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([3694.,  403., 2018., 2852., 2788., 1350.])

In [10]:
#Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([0, 1, 1, ..., 5, 5, 1])

##### i) akurasi

In [32]:
#Nilai akurasi
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred)
accuracy

0.1504424778761062

##### ii) f1_score

In [34]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(y_test, y_pred, average='weighted')

0.15076252130812148

##### iii) cross validation

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_naive = cross_val_score(modelnb, x, y, cv=5)
print(scores_naive)        
print(scores_naive.mean())
#metode svm 

[0.13113754 0.13449222 0.13182789 0.14935858 0.13229453]
0.13582215406420634


### Support Vector Machine

In [36]:
#Menentukan Variabel Independen dan Dependen 
#Variabel independen
x = df_fall.drop(["ACTIVITY"], axis = 1)
x.head()

#Variabel dependen
y = df_fall["ACTIVITY"]
y.head()

0    3
1    2
2    2
3    4
4    4
Name: ACTIVITY, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=42)
#disini digunakan untuk membagi data test dan training
# data testnya 20% dan trainingnya 80%
#dengan random state nya 42

#### a. Kernel RBF

In [38]:
from sklearn import svm
clf = svm.SVC(gamma='scale')
clf.fit(train_x,train_y)
#metode svm 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [39]:
pred_y = clf.predict(test_x)
print(pred_y)

[4 4 0 ... 0 0 0]


##### i) akurasi

In [40]:
from sklearn.metrics import accuracy_score
score = accuracy_score(test_y,pred_y)
print(score)

0.31461702776930117


##### ii) f1_score

In [41]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(test_y, pred_y, average='weighted')

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.23723237016407764

##### iii) cross validation

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_rbf_acc = cross_val_score(clf, x, y, cv=5)
print(scores_rbf_acc)        
print(scores_rbf_acc.mean())
#metode svm 

[0.32692894 0.31960964 0.3112603  0.32590104 0.33119462]
0.322978907808878


#### b. Kernel Sigmoid

In [48]:
from sklearn import svm
clf = svm.SVC(gamma='scale', kernel='sigmoid')
clf.fit(train_x,train_y)
#metode svm 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [49]:
pred_y = clf.predict(test_x)
print(pred_y)

[3 3 0 ... 0 1 0]


##### i) akurasi

In [50]:
from sklearn.metrics import accuracy_score
score = accuracy_score(test_y,pred_y)
print(score)

0.24351541043637473


##### ii) f1_score

In [51]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(test_y, pred_y, average='weighted')

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.17389288362022384

##### iii) cross validation

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_sigmoid= cross_val_score(clf, x, y, cv=5)
print(scores_sigmoid)        
print(scores_sigmoid.mean())

[0.25526075 0.26136017 0.24382057 0.27061698 0.24411855]
0.25503540331324603


#### c. Kernel LinearSVC 

In [53]:
from sklearn import svm
clf = svm.LinearSVC(max_iter=10000)
clf.fit(train_x,train_y)
#metode svm 

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=10000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [54]:
pred_y = clf.predict(test_x)
print(pred_y)

[0 0 0 ... 3 1 3]


##### i) akurasi

In [55]:
from sklearn.metrics import accuracy_score
score = accuracy_score(test_y,pred_y)
print(score)

0.28196521208422337


##### ii) f1_score

In [56]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(test_y, pred_y, average='weighted')

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.2286417541676477

##### iii) cross validation

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_linear= cross_val_score(clf, x, y, cv=5)
print(scores_linear)        
print(scores_linear.mean())

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[0.23970723 0.18999695 0.21513579 0.27061698 0.263978  ]
0.2358869914310638


/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


### K Nearest Neighbors

In [58]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [59]:
pred_ynn = neigh.predict(test_x)
print(pred_ynn)

[3 4 0 ... 4 0 0]


##### i) akurasi

In [60]:
score = accuracy_score(test_y,pred_ynn)
print(score)

0.6664632285627098


##### ii) f1_score

In [61]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_ynn)
f1_score(test_y, pred_ynn, average='weighted')

0.6655511041397189

##### iii) cross validation

In [62]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=5)
score= cross_val_score(knn, x, y, cv=10) 
print(score)        
print(score.mean())

[0.65874467 0.66057282 0.65405735 0.65527761 0.66666667 0.67155067
 0.69047619 0.68315018 0.65137615 0.67155963]
0.6663431941337669
