In [1]:
import pandas as pd
import numpy as np

## 1. READ DATASET FALL DETECTION

In [8]:
df_liver = pd.read_csv("liverpatient.csv")
#nampilin 5 data pertama dari csv, jumlah data bisa disesuain di parameternya
df_liver.head()

age  gender  tot_bilirubin  direct_bilirubin  tot_proteins  albumin  \
0   65  Female            0.7               0.1           187       16   
1   62    Male           10.9               5.5           699       64   
2   62    Male            7.3               4.1           490       60   
3   58    Male            1.0               0.4           182       14   
4   72    Male            3.9               2.0           195       27   

   ag_ratio  sgpt  sgot  alkphos  is_patient  
0        18   6.8   3.3     0.90           1  
1       100   7.5   3.2     0.74           1  
2        68   7.0   3.3     0.89           1  
3        20   6.8   3.4     1.00           1  
4        59   7.3   2.4     0.40           1

In [9]:
df_liver.dtypes

age                   int64
gender               object
tot_bilirubin       float64
direct_bilirubin    float64
tot_proteins          int64
albumin               int64
ag_ratio              int64
sgpt                float64
sgot                float64
alkphos             float64
is_patient            int64
dtype: object

In [10]:
#cek berapa bnyk record datanya
len(df_liver)

583

In [11]:
#cek berapa banyak elemen datanya
df_liver.count

<bound method DataFrame.count of      age  gender  tot_bilirubin  direct_bilirubin  tot_proteins  albumin  \
0     65  Female            0.7               0.1           187       16   
1     62    Male           10.9               5.5           699       64   
2     62    Male            7.3               4.1           490       60   
3     58    Male            1.0               0.4           182       14   
4     72    Male            3.9               2.0           195       27   
..   ...     ...            ...               ...           ...      ...   
578   60    Male            0.5               0.1           500       20   
579   40    Male            0.6               0.1            98       35   
580   52    Male            0.8               0.2           245       48   
581   31    Male            1.3               0.5           184       29   
582   38    Male            1.0               0.3           216       21   

     ag_ratio  sgpt  sgot  alkphos  is_patient  
0    

## 2. PREPROCESSING FALL DETECTION

In [12]:
df_liver.isnull().sum()

age                 0
gender              0
tot_bilirubin       0
direct_bilirubin    0
tot_proteins        0
albumin             0
ag_ratio            0
sgpt                0
sgot                0
alkphos             4
is_patient          0
dtype: int64

In [13]:
df_liver.dropna(subset=["alkphos"], axis=0, inplace=True)

In [14]:
df_liver.isnull().sum()

age                 0
gender              0
tot_bilirubin       0
direct_bilirubin    0
tot_proteins        0
albumin             0
ag_ratio            0
sgpt                0
sgot                0
alkphos             0
is_patient          0
dtype: int64

## 3. KLASIFIKASI FALL DETECTION

### Naive Bayes

In [16]:
#Menentukan Variabel Independen dan Dependen 
#Variabel independen
x = df_liver.drop(["gender", "is_patient"], axis = 1)
x.head()

#Variabel dependen
y = df_liver["is_patient"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: is_patient, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [18]:
from sklearn.naive_bayes import GaussianNB
#Mengaktifkan/memanggil/membuat fungsi klasifikasi naive bayes
modelnb = GaussianNB()

#Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([329., 134.])

In [19]:
#Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2,
       1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2,
       2, 1, 2, 2, 2, 2])

##### i) akurasi

In [20]:
#Nilai akurasi
from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred)
accuracy

0.603448275862069

##### ii) f1_score

In [22]:
from sklearn.metrics import f1_score

set(y_test) - set(y_pred)
f1_score(y_test, y_pred, average='weighted')

0.6143451571705187

##### iii) cross validation

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_naive = cross_val_score(modelnb, x, y, cv=5)
print(scores_naive)        
print(scores_naive.mean())
#metode svm 

[0.5862069  0.61206897 0.42241379 0.5        0.70434783]
0.5650074962518741


### Support Vector Machine

In [24]:
#Menentukan Variabel Independen dan Dependen 
#Variabel independen
x = df_liver.drop(["gender", "is_patient"], axis = 1)
x.head()

#Variabel dependen
y = df_liver["is_patient"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: is_patient, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state=42)
#disini digunakan untuk membagi data test dan training
# data testnya 20% dan trainingnya 80%
#dengan random state nya 42

#### a. Kernel RBF

In [26]:
from sklearn import svm
clf = svm.SVC(gamma='scale')
clf.fit(train_x,train_y)
#metode svm 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [27]:
pred_y = clf.predict(test_x)
print(pred_y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1]


##### i) akurasi

In [28]:
from sklearn.metrics import accuracy_score
score = accuracy_score(test_y,pred_y)
print(score)

0.6293103448275862


##### ii) f1_score

In [29]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(test_y, pred_y, average='weighted')

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.4861339171683999

##### iii) cross validation

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_rbf_acc = cross_val_score(clf, x, y, cv=5)
print(scores_rbf_acc)        
print(scores_rbf_acc.mean())
#metode svm 

[0.71551724 0.71551724 0.71551724 0.71551724 0.71304348]
0.7150224887556222


#### b. Kernel Sigmoid

In [31]:
from sklearn import svm
clf = svm.SVC(gamma='scale', kernel='sigmoid')
clf.fit(train_x,train_y)
#metode svm 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [32]:
pred_y = clf.predict(test_x)
print(pred_y)

[1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 2 2 1 1 1 2 2 1 1 2
 1 1 2 2 1 1 1 2 2 1 1 1 1 1 2 1 1 2 2 1 2 1 1 2 1 1 1 1 2 1 1 2 1 1 1 1 1
 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1 1 2 1 1 1 2 2 1 2 2 1 1 2 1 1
 2 2 1 1 1]


##### i) akurasi

In [33]:
from sklearn.metrics import accuracy_score
score = accuracy_score(test_y,pred_y)
print(score)

0.5517241379310345


##### ii) f1_score

In [34]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(test_y, pred_y, average='weighted')

0.5324005804145482

##### iii) cross validation

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_sigmoid= cross_val_score(clf, x, y, cv=5)
print(scores_sigmoid)        
print(scores_sigmoid.mean())

[0.62068966 0.57758621 0.63793103 0.61206897 0.70434783]
0.6305247376311843


#### c. Kernel LinearSVC 

In [36]:
from sklearn import svm
clf = svm.LinearSVC(max_iter=10000)
clf.fit(train_x,train_y)
#metode svm 

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=10000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [37]:
pred_y = clf.predict(test_x)
print(pred_y)

[1 1 2 1 1 1 1 2 2 1 1 2 1 1 1 2 2 1 1 1 1 1 1 1 1 2 1 2 2 1 1 2 2 2 1 1 1
 1 1 2 2 1 1 1 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 2 1 1 1 2 1 1 2 1 1 2 1 2 1
 1 1 2 1 1 2 1 2 1 1 2 1 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 2 1 1 1 2 2 1 2
 1 2 1 2 1]


##### i) akurasi

In [38]:
from sklearn.metrics import accuracy_score
score = accuracy_score(test_y,pred_y)
print(score)

0.6293103448275862


##### ii) f1_score

In [39]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_y)
f1_score(test_y, pred_y, average='weighted')

0.621367214134308

##### iii) cross validation

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

scores_linear= cross_val_score(clf, x, y, cv=5)
print(scores_linear)        
print(scores_linear.mean())

/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[0.71551724 0.71551724 0.31896552 0.72413793 0.59130435]
0.6130884557721139


/home/ambrose/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


### K Nearest Neighbors

In [41]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [42]:
pred_ynn = neigh.predict(test_x)
print(pred_ynn)

[1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 2 1 1 1 1
 1 1 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 2 1 2 2 1 1 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1]


##### i) akurasi

In [43]:
score = accuracy_score(test_y,pred_ynn)
print(score)

0.6379310344827587


##### ii) f1_score

In [44]:
from sklearn.metrics import f1_score

set(test_y) - set(pred_ynn)
f1_score(test_y, pred_ynn, average='weighted')

0.5718064263322884

##### iii) cross validation

In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=5)
score= cross_val_score(knn, x, y, cv=10) 
print(score)        
print(score.mean())

[0.71186441 0.6779661  0.69491525 0.62711864 0.55172414 0.70175439
 0.54385965 0.52631579 0.68421053 0.71929825]
0.6439027141201923
